### PR TITLE
prevent tar/cp/rm/mv from malicious filenames

### PR DESCRIPTION
**Pull request by M0ses**

### CODE REVIEW

**Comment by dirkmueller** [comment]
LGTM. Can you also add double quotes while you're at it to prevent further issues with spaces and similar?

**Comment by M0ses** [comment]
THX for hint - done.

**Comment by dirkmueller** [comment]
:+1:

**Comment by M0ses** [comment]
looks like I do not have pull permission.

**Comment by adrianschroeter** [comment]
@M0ses you should have permission now

**Comment by M0ses** [comment]
THX

**Pull request merged**
